<a href="https://colab.research.google.com/github/coder-omer/Numpy/blob/main/06_Self_Study_NumPy_Exercise_Student.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Çalışma

### NumPy Array'i Oluşturmak

In [ ]:
import numpy as np

In [ ]:
np.__version__

'1.19.5'

In [ ]:
# code here

array([1, 2, 3, 4, 5])

In [ ]:
a = np.array([1,2,3,4,5])
type(a)

numpy.ndarray

In [ ]:
np.array([3.14, 4, 2, 13], dtype = "int")

array([ 3,  4,  2, 13])

In [ ]:
np.array([3.14, 4, 2, 13], dtype = "float")

array([ 3.14,  4.  ,  2.  , 13.  ])

In [ ]:
# sifirdan array olusturma (np.zeros)

In [ ]:
# code here

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# code here

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# birlerden array olusturma (np.ones)

In [ ]:
# code here

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
# code here

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# belirlenen değerler ile doldurma (np.full)

In [ ]:
# code here

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

In [ ]:
# code here (arange)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [ ]:
# code here (linspace)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
# code here (random.normal)

array([[17.36153175, 13.13320486,  7.9751651 , 10.96652924],
       [15.88966379, 14.9596121 ,  0.79541802, 13.03982467],
       [11.16320473,  8.95138261, 11.24850164, 14.35247169]])

In [ ]:
# code here (random.randint)

array([[5, 8],
       [5, 2],
       [7, 5],
       [7, 7],
       [0, 5]])

### Özellikleri

* **ndim**: _boyut sayısı_
* shape: boyut bilgisi
* size: toplam eleman sayısı
* dtype: array veri tipi

In [ ]:
import numpy as np

In [ ]:
# code here(random.randint, hihg=10, size=10)

array([9, 8, 7, 8, 5, 3, 6, 8, 2, 8])

In [ ]:
a = np.random.randint(10, size = 10)
a

array([9, 8, 4, 1, 6, 7, 9, 5, 2, 3])

In [ ]:
# code here (find the dimension of a)

1

In [ ]:
# code here (find the shape of a)

(10,)

In [ ]:
# code here (find the size of a)

10

In [ ]:
# code here (find the dtype of a)

dtype('int32')

In [ ]:
# code here(assign your code to 'b', random.randint, hihg=20, size=(4,6))

In [ ]:
b

array([[14, 16,  3,  7,  1],
       [ 3, 16,  2,  6,  0],
       [15,  9,  8,  9, 19],
       [ 3, 10,  4,  6, 15]])

In [ ]:
b = np.random.randint(20, size = (4,6))

In [ ]:
# code here (find the dimension of b)

2

In [ ]:
# code here (find the shape of b)

(4, 6)

In [ ]:
# code here (find the size of b)

24

In [ ]:
# code here (find the dtype of b)

dtype('int32')

# Yeniden Şekillendirme (Reshaping)

In [ ]:
import numpy as np

In [ ]:
# code here (arange, start=1, stop=10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# code here (reshape (3,3) your coding above)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a = np.arange(1,10)

In [ ]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# code here (find the dimension of a)

1

In [ ]:
# code here (reshape a as (1,9) and assign to b)

In [ ]:
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
# code here (find the dimension of b)

2

### Array Birlestirme (Concatenation)

In [ ]:
import numpy as np

In [ ]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [ ]:
# code here (concatenate x and y)

array([1, 2, 3, 4, 5, 6])

In [ ]:
z = np.array([7,8,9])

In [ ]:
# code here (concatenate x, y and z)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# code here (concatenate z, y and x)

array([7, 8, 9, 4, 5, 6, 1, 2, 3])

In [ ]:
a = np.array([[1,2,3], 
              [4,5,6]])

In [ ]:
# code here (concatenate a and a)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
# code here (concatenate a and a)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# Array Ayırma (Splitting)

In [ ]:
import numpy as np

In [ ]:
x = np.array([1,2,3,99,99,3,2,1])

In [ ]:
# code here (split x from 3 and 5)

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [ ]:
# code here (do a tuple unpacking for above splitting in order of a,b,c)

In [ ]:
a

array([1, 2, 3])

In [ ]:
b

array([99, 99])

In [ ]:
c

array([3, 2, 1])

In [ ]:
#iki boyutlu ayırma

In [ ]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
# code here (split m)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [ ]:
# code here (split m)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

### Array Sıralama (Sorting)

In [ ]:
import numpy as np

In [ ]:
v = np.array([2,1,4,3,5])

In [ ]:
v

array([2, 1, 4, 3, 5])

In [ ]:
# code here (sort v)

array([1, 2, 3, 4, 5])

In [ ]:
# iki boyutlu array siralama

In [ ]:
m = np.random.normal(20,5, (3,3))

In [ ]:
m

array([[20.00086064, 11.4711052 , 28.44452052],
       [16.0648143 , 23.22445351, 15.02090679],
       [20.03722184, 22.39429448,  9.34939833]])

In [ ]:
# code here (sort m)

array([[11.4711052 , 20.00086064, 28.44452052],
       [15.02090679, 16.0648143 , 23.22445351],
       [ 9.34939833, 20.03722184, 22.39429448]])

In [ ]:
# code here (sort m)

array([[16.0648143 , 11.4711052 ,  9.34939833],
       [20.00086064, 22.39429448, 15.02090679],
       [20.03722184, 23.22445351, 28.44452052]])

# Index ile Elemanlara Erişmek

In [ ]:
import numpy as np
a = np.random.randint(10, size = 10)
a

array([3, 1, 3, 9, 8, 3, 2, 5, 7, 6])

In [ ]:
# code here

3

In [ ]:
# code here

6

In [ ]:
a[2], a[5], a[9] = [4, 0, 100]

In [ ]:
# code here

4

In [ ]:
# code here

0

In [ ]:
# code here

100

In [ ]:
m = np.random.randint(10, size = (3,5))
m

array([[8, 4, 2, 4, 6],
       [5, 6, 4, 2, 9],
       [8, 0, 0, 3, 6]])

In [ ]:
# code here

8

In [ ]:
# code here

6

In [ ]:
# code here

In [ ]:
m[1, 4]

9

In [ ]:
# code here (look at the below array)

In [ ]:
m

array([[ 8,  4,  2,  4,  6],
       [ 5,  6,  4,  2, 99],
       [ 8,  0,  0,  3,  6]])

In [ ]:
# code here

In [ ]:
m[2, 3]

3

In [ ]:
# code here (look at the below array)

In [ ]:
m

array([[  8,   4,   2,   4,   6],
       [  5,   6,   4,   2,  99],
       [  8,   0,   0, 111,   6]])

# Slicing ile Elemanlara Erişmek (Array Alt Kümesine Erişmek)

In [ ]:
import numpy as np

In [ ]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
# code here

array([20, 21, 22])

In [ ]:
# code here

array([20, 21, 22])

In [ ]:
# code here

array([23, 24, 25, 26, 27, 28, 29])

In [ ]:
# code here

array([21, 23, 25, 27, 29])

In [ ]:
# code here

array([20, 22, 24, 26, 28])

In [ ]:
# code here

array([22, 24, 26, 28])

In [ ]:
# code here

array([20, 23, 26, 29])

In [ ]:
#iki boyutlu slice islemleri

In [ ]:
m = np.random.randint(10, size = (5,5))

In [ ]:
m

array([[2, 1, 8, 3, 8],
       [4, 3, 2, 3, 5],
       [5, 9, 3, 1, 3],
       [3, 1, 6, 9, 4],
       [6, 0, 9, 9, 0]])

In [ ]:
# code here

array([2, 4, 5, 3, 6])

In [ ]:
# code here

array([1, 3, 9, 1, 0])

In [ ]:
# code here

array([8, 5, 3, 4, 0])

In [ ]:
m

array([[2, 1, 8, 3, 8],
       [4, 3, 2, 3, 5],
       [5, 9, 3, 1, 3],
       [3, 1, 6, 9, 4],
       [6, 0, 9, 9, 0]])

In [ ]:
# code here

array([2, 1, 8, 3, 8])

In [ ]:
# code here

array([2, 1, 8, 3, 8])

In [ ]:
# code here

array([4, 3, 2, 3, 5])

In [ ]:
# code here

array([[2, 1, 8],
       [4, 3, 2]])

In [ ]:
# code here

array([[2, 1],
       [4, 3],
       [5, 9],
       [3, 1],
       [6, 0]])

In [ ]:
m

array([[2, 1, 8, 3, 8],
       [4, 3, 2, 3, 5],
       [5, 9, 3, 1, 3],
       [3, 1, 6, 9, 4],
       [6, 0, 9, 9, 0]])

In [ ]:
# code here

array([[4, 3],
       [5, 9]])

# Alt Küme Üzerinde İşlem Yapmak

In [ ]:
import numpy as np
a = np.random.randint(10, size = (5, 5))
a

array([[3, 5, 0, 7, 2],
       [8, 5, 4, 6, 1],
       [9, 0, 5, 9, 5],
       [7, 6, 6, 6, 3],
       [4, 3, 8, 7, 6]])

In [ ]:
# code here

array([[3, 5],
       [8, 5],
       [9, 0]])

In [ ]:
# code here

array([[99999,     5],
       [    8,   888],
       [    9,     0]])

In [ ]:
a

array([[99999,     5,     0,     7,     2],
       [    8,   888,     4,     6,     1],
       [    9,     0,     5,     9,     5],
       [    7,     6,     6,     6,     3],
       [    4,     3,     8,     7,     6]])

In [ ]:
m = np.random.randint(10, size = (5, 5))
m

array([[8, 1, 4, 0, 2],
       [4, 0, 3, 0, 6],
       [4, 1, 4, 0, 3],
       [1, 8, 0, 8, 9],
       [6, 0, 1, 2, 4]])

In [ ]:
# code here

array([[7, 0],
       [7, 5],
       [7, 4]])

In [ ]:
# code here

array([[9999,    0],
       [   9,    3],
       [   5,    1]])

In [ ]:
m

array([[9, 0, 0, 8, 9],
       [9, 3, 4, 1, 9],
       [5, 1, 2, 1, 5],
       [8, 2, 3, 8, 0],
       [5, 7, 6, 3, 8]])

# Fancy Index ile Elemanlara Erişmek

In [ ]:
import numpy as np
v = np.arange(0, 30, 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [ ]:
# code here

3

In [ ]:
# code here

9

In [ ]:
# code here

15

In [ ]:
# code here

[3, 9, 15]

In [ ]:
al_getir = [1,3,5]

In [ ]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [ ]:
# code here

array([ 3,  9, 15])

In [ ]:
#iki boyutta fancy

In [ ]:
m = np.arange(9).reshape((3,3))

In [ ]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [ ]:
m[satir, sutun]

array([1, 5])

In [ ]:
#basit index ile fancy index

In [ ]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
m[0, [1,2]]

array([1, 2])

In [ ]:
#slice ile fancy

In [ ]:
m[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

# Koşullu Eleman İşlemleri

In [ ]:
import numpy as np
v = np.array([1, 2, 3, 4, 5])

In [ ]:
v < 3

array([ True,  True, False, False, False])

In [ ]:
v[v < 3]

array([1, 2])

In [ ]:
# code here

In [ ]:
v[v > 3]

array([4, 5])

In [ ]:
# code here

array([3, 4, 5])

In [ ]:
# code here

array([1, 2, 3])

In [ ]:
# code here

array([3])

In [ ]:
# code here

array([1, 2, 4, 5])

In [ ]:
v

array([1, 2, 3, 4, 5])

In [ ]:
# code here

array([ 2,  4,  6,  8, 10])

In [ ]:
# code here

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [ ]:
# code here

array([ 1,  4,  9, 16, 25], dtype=int32)

# Matematiksel İşlemler

Bu bölüm bilgi ve tekrar maksatlı konulmuştur.

In [ ]:
import numpy as np
v = np.array([1, 2, 3, 4, 5])

In [ ]:
v - 1

array([0, 1, 2, 3, 4])

In [ ]:
v * 5

array([ 5, 10, 15, 20, 25])

In [ ]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [ ]:
#ufunc

In [ ]:
np.subtract(v, 1)

array([0, 1, 2, 3, 4])

In [ ]:
np.add(v, 1)

array([2, 3, 4, 5, 6])

In [ ]:
np.multiply(v,4)

array([ 4,  8, 12, 16, 20])

In [ ]:
np.divide(v, 3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [ ]:
v**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [ ]:
v**3

array([  1,   8,  27,  64, 125], dtype=int32)

In [ ]:
np.power(v, 3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [ ]:
v % 2

array([1, 0, 1, 0, 1], dtype=int32)

In [ ]:
np.mod(v, 2)

array([1, 0, 1, 0, 1], dtype=int32)

In [ ]:
np.absolute(np.array([-3]))

array([3])

In [ ]:
np.sin(360)

0.9589157234143065

In [ ]:
np.cos(180)

-0.5984600690578581

In [ ]:
v = np.array([1,2,3])

In [ ]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [ ]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [ ]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125])

In [ ]:
?np

# İstatistiksel Hesaplamalar

In [ ]:
v

array([1, 2, 3, 4, 5])

In [ ]:
np.mean(v)

2.0

In [ ]:
v.sum()

6

In [ ]:
v.min()

1

* np.mean(arr,axis=0) | Returns mean along specific axis

* arr.sum() | Returns sum of arr

* arr.min() | Returns minimum value of arr

* arr.max(axis=0) | Returns maximum value of specific axis

* np.var(arr) | Returns the variance of array

* np.std(arr,axis=1) | Returns the standard deviation of specific axis

* arr.corrcoef() | Returns correlation coefficient of array

# NumPy ile İki Bilinmeyenli Denklem Çözümü

In [ ]:
import numpy as np

**5 * x0 + x1 = 12  
x0 + 3 * x1 = 10**

In [ ]:
a = np.array([[5,1], [1,3]])
b = np.array([12,10])

In [ ]:
a

array([[5, 1],
       [1, 3]])

In [ ]:
b

array([12, 10])

In [ ]:
x = np.linalg.solve(a, b)
x

array([1.85714286, 2.71428571])