In [2]:
import numpy as np

In [3]:
a = np.array([5,6,9])

In [4]:
a[0]

5

In [5]:
a[1]

6

In [6]:
a = np.array([[1,2],[3,4],[5,6]])

In [7]:
a.ndim

2

In [8]:
a = np.array([5,6,9])

In [10]:
a.ndim

1

In [11]:
a.itemsize

8

In [12]:
a.size

3

In [13]:
a

array([5, 6, 9])

In [14]:
a.dtype

dtype('int64')

In [16]:
a = np.array([[1,2],[3,4],[5,6]], dtype=np.float64)

In [17]:
a.itemsize

8

In [18]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [19]:
a.shape

(3, 2)

In [20]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
l = range(5)

In [23]:
l

range(0, 5)

In [24]:
l[0]

0

In [25]:
l[1]

1

In [26]:
np.arange(1,5)

array([1, 2, 3, 4])

In [27]:
np.arange(1,5,2)

array([1, 3])

In [28]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [29]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [30]:
a = np.array([[1,2],[3,4],[5,6]])

In [31]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [32]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [33]:
a.shape

(3, 2)

In [34]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [36]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [37]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [38]:
a.min()

1

In [40]:
a.max()

6

In [41]:
a.sum()

21

In [42]:
a.sum(axis=0)

array([ 9, 12])

In [43]:
a.sum(axis=1)

array([ 3,  7, 11])

In [44]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [45]:
np.std(a)

1.707825127659933

In [47]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [48]:
a

array([[1, 2],
       [3, 4]])

In [49]:
b

array([[5, 6],
       [7, 8]])

In [50]:
a + b

array([[ 6,  8],
       [10, 12]])

In [51]:
a * b

array([[ 5, 12],
       [21, 32]])

In [52]:
a / b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [53]:
a.dot(b)

array([[19, 22],
       [43, 50]])