<a href="https://colab.research.google.com/github/coder-omer/Numpy/blob/main/19012022_slicing_and_indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
n = [6,7,8]

In [ ]:
n[0:2]

[6, 7]

In [ ]:
n[-1]

8

In [ ]:
a = np.array([6,7,8])

In [ ]:
a[0:2]

array([6, 7])

In [ ]:
a[-1]

8

In [ ]:
a = np.array([[6,7,8],[1,2,3],[9,3,2]])

In [ ]:
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [ ]:
a[1,2]

3

In [ ]:
a[0:2,2]

array([8, 3])

In [ ]:
a[1:3,1]

array([2, 3])

In [ ]:
a[-1]

array([9, 3, 2])

In [ ]:
a[-1,0:2]

array([9, 3])

In [ ]:
a[:,1:3]

array([[7, 8],
       [2, 3],
       [3, 2]])

In [ ]:
a = np.array([[6,7,8],[1,2,3],[9,3,2]])

In [ ]:
for row in a:
  print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [ ]:
for cell in a.flat:
  print(cell)

6
7
8
1
2
3
9
3
2


In [ ]:
a = np.arange(6).reshape(3,2)
b = np.arange(6,12).reshape(3,2)

In [ ]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [ ]:
a = np.arange(30).reshape(2,15)

In [ ]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [ ]:
np.hsplit(a,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]), array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]), array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [ ]:
result = np.hsplit(a,3)

In [ ]:
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [ ]:
result = np.vsplit(a,2)

In [ ]:
result[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [ ]:
result[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [ ]:
a = np.arange(12).reshape(3,4)

In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b = a>4

In [ ]:
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
arr = np.arange(0,11)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[2:5]

array([2, 3, 4])

In [ ]:
arr = np.arange(1,8)
arr[arr>4]

array([5, 6, 7])

In [ ]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,50]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 50]])

In [ ]:
arr_2d[0,2]

15