<a href="https://colab.research.google.com/github/coder-omer/Numpy/blob/main/calisma_20012022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a = []
sayı = int(input("Gireceğiniz sayı adedini giriniz: "))
for i in range(1, sayı + 1):
    b = int(input("Sayı giriniz: "))
    a.append(b)
print("Second largest element is:", sorted(a)[-2])

Gireceğiniz sayı adedini giriniz: 3
Sayı giriniz: 1
Sayı giriniz: 2
Sayı giriniz: 3
Second largest element is: 2


In [ ]:
def SecondBig(numbers):
  return sorted(set(numbers))[-2]

In [ ]:
SecondBig([-2,3,4,5,19,65,78,90])

78

In [ ]:
a = [1, 2, 3, 4]
b = [2, 3, 4, 5]

In [ ]:
ab = []

In [ ]:
for i in range(0, len(a)):
  ab.append(a[i] * b[i])

In [ ]:
ab

[2, 6, 12, 20]

In [ ]:
import numpy as np

In [ ]:
a = np.arange()

In [ ]:
a1 = np.array([1,2,3,4])
b1 = np.array([2,3,4,5])

In [ ]:
a1 * b1

array([ 2,  6, 12, 20])

In [ ]:
a1 = np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4]])
b1 = np.array([[2,3,4,5],[2,3,4,5],[2,3,4,5]])

In [ ]:
a1

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [ ]:
b1

array([[2, 3, 4, 5],
       [2, 3, 4, 5],
       [2, 3, 4, 5]])

In [ ]:
a1 * b1

array([[ 2,  6, 12, 20],
       [ 2,  6, 12, 20],
       [ 2,  6, 12, 20]])

In [ ]:
my_matrix = [[1,2,3,4],[1,2,3,4],[1,2,3,4]]
my_matrix

[[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]]

In [ ]:
l = range(1000)

In [ ]:
import sys

In [ ]:
print("size of one item in list: ", sys.getsizeof(5))

size of one item in list:  28


In [ ]:
print("size of all item in list: ", sys.getsizeof(5) * len(l))

size of all item in list:  28000


In [ ]:
a = np.arange(1000)

In [ ]:
print("size of one item in list: ", a.itemsize)

size of one item in list:  8


In [ ]:
print("size of all item in list: ", a.itemsize * a.size)

size of all item in list:  8000


In [ ]:
print(a.size)

1000


In [ ]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [ ]:
my_array = np.array(my_list)
my_array

array([1, 2, 3])

In [ ]:
my_array1 = np.array([1,2,3])
my_array1

array([1, 2, 3])

In [ ]:
my_list = [[1,2,3],[4,5,6],[7,8,9]]
my_list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(my_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
my_list = [[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]]
my_list

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]]

In [ ]:
np.array(my_list)

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])