<a href="https://colab.research.google.com/github/coder-omer/Numpy/blob/main/Numpy_kutuphaneler_ve_NumPy_kutuphanesinin_temelleri.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# KÜTÜPHANELER VE NumPy KÜTÜPHANESİ TEMELLERİ


# 1. Kütüphaneler ve Kütüphane Yükleme



Python kütüphaneleri ve paketleri, günlük yaşamda belirli programlama ve veri yönetimi işlerimizi kolaylaştırmak adına hazır modülleri ve fonksiyonları barındırır. Kütüphanelerdeki bu hazır fonksiyonlar sayesinde, kod yazma hızımız ve pratikliğimiz artar. Python için yaklaşık 137 bin kütüphane ve 198 bin paket, program geliştiricilerin kullanımına açıktır. 

Veri yönetimi ve işleme, makine öğrenmesi (machine learning), veri görselleştirme, görüntü işleme, web'ten veri ayıklama, haritalama vb. amaçlarla oluşturulmuş kütüphanelerin kullanımı gittikçe yaygınlaşmaktadır. 

| Kütüphane     | İşlevi           | 
|--------------|----------------|
| NumPy    | Çok boyutlu diziler ve matrisler|
| pandas    | Veri analizi ve veri işleme | 
| matplotlib    | Veri görselleştirme| 
| keras    | Derin öğrenme   |
| TensorFlow  | Makine öğrenmesi   | 
| scipy    | Bilimsel hesaplama ve teknik programlama| 
| SQLAlchemy  | SQL veri tabanı yönetimi   | 
| BeautifulSoup       | HTML ve XML dökümanlardan veri ayıklama    | 
| scikit-learn     | Makine öğrenmesi    | 
| seaborn      | Veri görselleştirme   | 
| bokeh      | Veri görselleştirme    | 
| PyGame       | Oyun geliştirme    | 
| PyTorch      | Makine öğrenmesi   | 
| GeoPandas      | Konumsal veri analizi ve haritalama    | 
| ArcPy      | Konumsal veri analizi    | 
| Shapely      | Geometrik şekil görselleştirme  | 
| Rasterio      | Raster veri analizi    | 
| folium      | Harita oluşturma    | 

Bu paketlerin yüklenebilmesi için __!pip install [paket ismi]__ komutunun kullanılması gerekmektedir. 

Bir kütüphanenin çalışması için, başka kütüphanelerin yüklü olması gerekebilir (Dependency). Örneğin, [matplotlib websayfasına](https://matplotlib.org/users/installing.html) baktığımızda, bu kütüphanenin 3.2.1 versiyonunun çalışması için Python (>= 3.6), FreeType (>= 2.3) ,libpng (>= 1.2), NumPy (>= 1.1),setuptools, cycler (>= 0.10.0), dateutil (>= 2.1), kiwisolver (>= 1.0.0),pyparsing modüllerinin ve kütüphanelerinin sistemimizde yüklü olması gerekir. 

Anaconda üzerinde halihazırda yüklü olmayan descartes kütüphanesini yükleyelim: 


In [ ]:
!pip install descartes

Sistemde yüklü olan bir paketi / kütüphaneyi çalışma ekranımızdaki kodun içine dahil etmek için **import** komutu kullanılır. 

Bir paketin /kütüphanenin sadece tek bir fonksiyonunu çağırmak istersek 
**from [paket/kütüphane ismi] import [fonksiyon ismi]** 
komutu kullanılır.

Örneğin çemberin alanını ve çevresini hesaplamak için Anaconda içinde hazırda yüklü olan **math** kütüphanesinden **pi** sayısını çağırılım. 

In [ ]:
import math
from math import pi

r = 0.43 # yarıçap
C = 2*math.pi*r
A = math.pi*r*r
print("Çevre: " + str(C))
print("Alan: " + str(A))

Çevre: 2.701769682087222
Alan: 0.5808804816487527


Bir başka örnek;

Ayın, Dünya etrafındaki yörüngesinin mükemmel bir çember olduğunu varsayalım. _r_ (km) cinsinden bu yörüngenin yarıçapı olsun. Ayın, 12 derece hareket etmesiyle aldığı yolun uzunluğunu hesaplayalım. 

Çember yayının formülü  ***r * phi***

*phi*, burada radyan cinsinden açıdır. Dolayısıyla verilen açıyı, derece cinsinden radyan cinsine çevirmemiz gerekir. 

In [ ]:
# Yarıçap uzunluğunun tanımı
r = 192500

# math paketinden radians fonksiyonunu çekelim. 
from math import radians

# Formülü uygulayalım.
uzaklık = r * radians(12)

# Sonucu ekrana verelim.
print(uzaklık)

40317.10572106901


Fonksiyonlar şayet bir paketin alt paketi içinde bulunuyorsa, bu alt paketin ismi de eklenmelidir. Örneğin, inv() fonksiyonu scipy paketinin linalg altpaketindedir. Dolayısıyla:

`from scipy.linalg import inv`

şeklinde komut yazılır. 

Atayacağımız fonksiyona kendimiz bir isim de verebiliriz. Örneğin inv fonksiyonuna my_inv ismini vermek isteyelim. Dolayısıyla komutun sonuna as komutunu da eklememiz gerekir: 

`from scipy.linalg import inv as my_inv`


# 2. NumPy Kütüphanesi

NumPy, Python'daki bilimsel programlama ve özellikle veri analizi için kullanılan en temel kütüphanedir. Çok fazla sayıda matematiksel ve bilimsel Python paketinin temelini oluşturur. Standart Python içeriğinin yetersiz kaldığı bütün veri analizi hesaplamalarında yardımcı olur. NumPy kütüphanesini kullanmasını bilen bir kullanıcı, diğer bilimsel Python paketlerini de kullanabilecektir. 

NumPy, çoğunlukla çok boyutlu diziler ve bu dizilere ilişkin hazır fonksiyonlar barındırır. 

Numpy eğer çalışma sisteminizde yüklü değilse, aşağıdaki komut ile yüklenir. 

`!pip install numpy`

NumPy sisteme yüklendikten sonra, kütüphaneyi çalışma sayfamıza atamak için aşağıdaki komut çalıştırılır. Kütüphanenin ismi veri bilimi camiasında **np** şeklinde kısaltılır. 

`import numpy as np`

# 3. *ndarray*: NumPy Kütüphanesinin Kalbi

NumPy kütüphanesi, ***ndarray*** nesnesinin üzerinde temellendirilmiştir (ndarray burada N-boyutlu dizi, İngilizcesi N-dimensional array teriminin kısaltmasına karşılık gelir). Bu nesne, çok boyutlu, heterojen, elemanları belirtilmiş dizilerdir.

Dizideki boyut ve eleman sayısı, dizinin boyutunu (***shape***) verir. Dizinin boyutu tanımlandıktan sonra, değişmeden kalır. 

İlk ndarray'imizi, `array()` fonksiyonu ile oluşturalım. 

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3])

In [ ]:
a

array([1, 2, 3])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a.ndim # bu dizi kaç boyutludur?

1

In [ ]:
a.size # bu dizide kaç eleman vardır?

3

In [ ]:
a.shape # bu dizi kaç sütün ve satırdan oluşmaktadır?

(3,)

In [ ]:
a.dtype # dizide bulunan elemanların veri tipi nedir?

dtype('int64')

In [ ]:
b = np.array([[1.3, 2.4],[0.3, 4.1]])
b

array([[1.3, 2.4],
       [0.3, 4.1]])

In [ ]:
b.ndim

2

In [ ]:
b.size

4

In [ ]:
b.shape

(2, 2)

Özetle ndarray dizileri üzerinde temel sorgulamaları yapabileceğimiz yöntemler aşağıdaki tabloda özetlenmiştir: 

| Yöntem     | İşlevi           | 
|--------------|----------------|
| `.ndim `   | Dizinin boyutunu verir.|
| `.size`   | Dizide kaç eleman olduğunu gösterir. | 
| `.shape`    | Dizinin kaç satır ve kaç sütundan oluştuğunu gösterir.| 


### Alıştırma 1


7 kişilik bir NBA basketbol takımındaki oyuncuların inç cinsinden boylarının dizisi verilmiş olsun. Bu uzunlukları metre cinsine çevirelim. 

In [ ]:
boy = [74.180, 74.215, 72.210, 72.210, 73.188, 69.176, 69.209]
print(type(boy))
# Python'da standart bir liste oluşturduk. Şimdi bunu NumPy kullanmadan metre cinsine çevirmeye çalışalım.
boy_m = boy * 0.0254

<class 'list'>


TypeError: ignored

Listemizi girdikten sonra veri tipini kontrol ettik ve sorgu sonucunda elimizdekinin bir liste olduğunu gördük. Akabinde listeyi tek bir skaler float ile çarptık ve bir hata ile karşılaştık. Python'da standart bir listedeki / dizideki tüm elemanları aynı anda tek bir sayı ile çarpmak olanaklı değildir. Bunu yapabilmemiz için, her elemanı tek tek çarpmamız gerekecekti. Bu da daha uzun bir kod yazmak için zaman kaybına sebep olacaktı. Dolayısıyla, listemizi bir NumPy dizisine çevirerek bu zaman kaybını önleyebiliriz. Çünkü NumPy kütüphanesi, bu dizi üzerinde aritmetik işlem yapmamıza en kısa yoldan izin verecek. 

In [ ]:
import numpy as np

# ndarray oluşturalım.
np_boy = np.array(boy)

# Ekrana diziyi ve veri tipini yazdıralım
print(np_boy)
print(type(np_boy))

# inç'ten metreye çevirelim

np_boy_m = np_boy*0.0254

# Ekrana yazdıralım.
print(np_boy_m)

[74.18  74.215 72.21  72.21  73.188 69.176 69.209]
<class 'numpy.ndarray'>
[1.884172  1.885061  1.834134  1.834134  1.8589752 1.7570704 1.7579086]


### Alıştırma 2

Bu oyuncuların ağırlıklarının listesini ekleyerek, Vücüt Kitle İndekslerini hesaplayalım. 

__VKİ = ağırlık / (boy)^2__

In [ ]:
agirlik = [79.1, 78.2, 79.2, 79.0, 76.1, 72.1, 73.4]  # Oyuncuların ağırlıklarını içeren listeyi girelim. 

agirlik_np = np.array(agirlik) # Bu listeyi bir NumPy dizisine çevirelim. 

print(agirlik_np)

[79.1 78.2 79.2 79.  76.1 72.1 73.4]


In [ ]:
vki = np.array(agirlik_np)/np.array(np_boy_m)**2 # Boy ve ağırlığı içeren NumPy dizileri üzerinden formülümüzü uygulayalım.

print(vki) # Vücut kitle indekslerini barındıran NumPy dizisini yazdıralım.

[22.28103661 22.00675134 23.54306807 23.48361588 22.02102169 23.35376682
 23.75218014]


## 3.1 *ndarray* Altkümeleri

NumPy dizileri de, Python listeleri gibi köşeli parantezler kullanılarak altkümelerine ayrılabilir. 

In [ ]:
x = [4 , 9 , 6, 3, 1]
x[1]

9

In [ ]:
import numpy as np
y = np.array(x)
y[1]

9

Altkümelenecek elemanlar için bir koşul da belirtilebilir. Örneğin:

In [ ]:
yuksek = y > 5
y[yuksek]

array([9, 6])

### Alıştırma 3

Bir önceki, vücut kitle indeksi hesaplamasına göre, değerlerin 23'ten küçük olup olmadığını kontrol edelim. 

In [ ]:
# hafif dizisini oluşturalım
hafif = vki < 23
# Ekrana yazdıralım.
print(hafif)

[ True  True False False  True False False]


Şimdi de, 23'ten küçük olan vücüt kitle indekslerini ekrana verelim.

In [ ]:
print(vki[hafif])

[22.28103661 22.00675134 22.02102169]


Dikkat edileceği üzere; hafif dizisi vki dizisi için bir koşul oluşturmaktadır. vki dizisi içindeki 23'ten küçük değerleri aramaktadır. 23'ten küçük değerleri ekrana verebilmemiz ya da başka isimle kaydedebilmemiz için bu koşul dizisini köşeli parantez içine alarak vki dizisini filtreledik. 

### Alıştırma 4

In [ ]:
import numpy as np

agirlik = [79.1, 78.2, 79.2, 79.0, 76.1, 72.1, 73.4]
boy = [1.88, 1.88, 1.83, 1.83, 1.85, 1.75, 1.75]

# Ağırlık ve boy listelerini NumPy dizisine çevirelim.
agirlik_np = np.array(agirlik)
boy_np = np.array(boy)

# Ağırlık dizisindeki 5. elemanı ekrana verelim. 
print(agirlik_np[4])

# Boy dizisinin 4. ve 5. elemanlarından oluşan alt diziyi dilimleyelim.
print(boy_np[3:5])

76.1
[1.83 1.85]


### Alıştırma 5

Sporcuların hem boyunu, hem de ağırlığını içeren iki boyutlu bir liste oluşturalım:

In [ ]:
oyuncu = [[79.1,1.88],
           [78.2,1.88],
           [79.2,1.83],
           [79.0,1.83],
           [76.1,1.85],
           [72.1,1.75],
           [73.4,1.75]]

import numpy as np

# Bu listeyi NumPy dizisine (ndarray) çevirelim.
np_oyuncu = np.array(oyuncu)

# Bu ndarray'in türüne ve boyutlarına bakalım.
print(type(np_oyuncu))

print(np_oyuncu.shape)

<class 'numpy.ndarray'>
(7, 2)


In [ ]:
# Bu ndarray'in 5.ci satırına bakalım.
print(np_oyuncu[4,:])

[76.1   1.85]


In [ ]:
# oyuncu ndarray'inde boy sütununu ekrana verelim.
print(np_oyuncu[:,1])

[1.88 1.88 1.83 1.83 1.85 1.75 1.75]


In [ ]:
# 6.cı oyuncunun ağırlığına bakalım.
print(np_oyuncu[5,0])

72.1


## 3.2 Temel Diziler

`zeros()` fonksiyonu, belirtilen boyutlarda elemanları tamamen sıfırlardan oluşan bir dizi üretir. 

In [ ]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

`ones()` fonksiyonu da benzer şekilde, tamamen 1 elemanlarından oluşan bir dizi üretir.

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

`arange()` fonksiyonu, belirtilen aralık ve kurallar dahilinde sıralı NumPy dizileri üretir. Örneğin; 0 ile 10 arasında (10 hariç!) birer birer artan elemanlardan oluşan bir dizi oluşturmak istiyorsanız:

In [ ]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

4 ile 10 arasında üretelim:

In [ ]:
np.arange(4, 10)

array([4, 5, 6, 7, 8, 9])

0-12 arasında üçer üçer artan elemanlardan oluşan bir dizi:

In [ ]:
np.arange(0, 12, 3)

array([0, 3, 6, 9])

Bu artış, ondalık sayılarla da olabilir: 

In [ ]:
np.arange(0, 6, 0.6)

array([0. , 0.6, 1.2, 1.8, 2.4, 3. , 3.6, 4.2, 4.8, 5.4])

0-12 arasında 3x4 boyutlarında bir dizi üretelim. Burada `.reshape()` yöntemi ile istediğimiz boyutları belirteceğiz.

In [ ]:
np.arange(0, 12).reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

`linspace()` fonksiyonu, `arange()` fonksiyonuna benzemektedir. Ancak dizinin ne kadar artacağını belirtmek yerine, dizinin ilk ve son elemanları arasında (ilk ve son dahil) kaç eleman bulunacağını belirterek kullanılır. Örneğin; 0 ile 10 arasında 5 adet sayı doğrusu üzerinde eşit aralıklarda bulunan ardışık elemanlar oluşan diziyi yazalım. 

In [ ]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

`random()` fonksiyonu ise, belirtilen sayıda ve boyutta rastgele eleman atar ve diziyi oluşturur.

In [ ]:
np.random.random(3)

array([0.79365617, 0.21097054, 0.19888247])

In [ ]:
np.random.random((3,3))

array([[0.27144186, 0.03594129, 0.82112749],
       [0.61915416, 0.67697588, 0.39429009],
       [0.13123979, 0.89936873, 0.28944322]])


## 3.3 *ndarray* Üzerinde İki Boyutlu Aritmetik İşlemler

In [ ]:
import numpy as np

a = np.arange(4)

a

array([0, 1, 2, 3])

In [ ]:
a + 4

array([4, 5, 6, 7])

In [ ]:
a * 2

array([0, 2, 4, 6])

In [ ]:
b = np.arange(4,8)

b

array([4, 5, 6, 7])

In [ ]:
a + b 

array([ 4,  6,  8, 10])

In [ ]:
a - b

array([-4, -4, -4, -4])

In [ ]:
a * b

array([ 0,  5, 12, 21])

![](elementwise_addition.png)

Görüleceği üzere, NumPy dizileri elemanter düzeyde, yani her iki dizideki aynı indeksli eleman üzerinde aritmetik işlemi uygulayarak sonucu verir. Şekildeki örnekte, elemanter toplama işlemini görmektesiniz. 

![Elemanter Toplama İşlemi](https://drive.google.com/uc?id=1CCi4V6AoAJ4UXLgqIkqFqRftmpA-e6LW)

In [ ]:
a * np.sin(b) # B dizisinin elemanlarının sinüs fonksiyonu karşılıklarını a dizisi ile çarpalım.

array([-0.        , -0.95892427, -0.558831  ,  1.9709598 ])

In [ ]:
a * np.sqrt(b) # B dizisinin elemanlarının kareköklerini a dizisi ile çarpalım. 

array([0.        , 2.23606798, 4.89897949, 7.93725393])

### Alıştırma 6

In [ ]:
A = np.arange(0, 9).reshape(3, 3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
B = np.ones((3, 3))
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
A*B

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

## 3.4 Matris Çarpımı

NumPy aritmetik işlemlerinde uyguladığımız elemanter düzeydeki çarpma işlemi (*), matris çarpımından farklıdır. 

Matris çarpımı için `dot()` fonksiyonu kullanılır. 

![Matris Çarpımı](https://drive.google.com/uc?id=1GtZRMTI1gQbLJe1HNqzDQQlpdU3tj9-y)

Bir önceki alıştırmada kullandığımız A ve B matrisleri kullanalım. 

In [ ]:
np.dot(A,B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [ ]:
A.dot(B) # bir diğer yazım şekli. 

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

Unutmayalım ki, matris çarpımında A * B ile B * A'nın sonuçları aynı değildir.

In [ ]:
B.dot(A)

array([[ 9., 12., 15.],
       [ 9., 12., 15.],
       [ 9., 12., 15.]])

## 3.5 Artış - Azalış Operatörleri

In [ ]:
a = np.arange(4) # 0'dan başlayan dört elemanlı bir dizi oluşturalım.
a

array([0, 1, 2, 3])

In [ ]:
a += 1  # bu dizideki elemanların her birini 1 artıralım.
a

array([1, 2, 3, 4])

In [ ]:
a -= 1 # yeni dizideki elemanların her birini 1 azaltalım. 
a

array([0, 1, 2, 3])

In [ ]:
a += 4 # yeni dizideki elemanların her birini 4 artıralım
a

array([4, 5, 6, 7])

In [ ]:
a *= 2 # yeni dizideki elemanların her birini 2 ile çarpalım.
a

array([ 8, 10, 12, 14])

Görüleceği üzere dizi üzerine uygulanan her işlem sonucunda yeni dizi, işlem sonuçları ile atanmaktadır. Ardışık işlem kullanılan (iterasyon) çalışmalarda artırma ve azaltma operatörleri oldukça işe yarayacaktır. 

## 3.6 Matematiksel ve Trigonometrik Operatörler

In [ ]:
B = np.arange(3)
B

array([0, 1, 2])

In [ ]:
np.exp(B) # Dizinin eksponansiyel üstel değerleri

array([1.        , 2.71828183, 7.3890561 ])

In [ ]:
np.sqrt(B) # Dizinin karekök değerleri

array([0.        , 1.        , 1.41421356])

In [ ]:
C = np.array([2., -1., 4.])
C
np.add(B,C) # add() fonksiyonu ile de elemanter toplam işlemi yapılabilir. 

array([2., 0., 6.])

In [ ]:
np.average(C) # C dizisinin elemanlarının ağırlıklı ortalaması

1.6666666666666667

In [ ]:
D = np.array([2.31124, 1.45345, 5.3212])
np.ceil(D)   # D dizisinin elemanları yukarı yönlü yuvarlanır.

array([3., 2., 6.])

In [ ]:
E = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0]) 
np.floor(E)   # E dizisinin elemanları aşağı yönlü yuvarlanır.

array([-2., -2., -1.,  0.,  1.,  1.,  2.])

In [ ]:
F = np.array([[10, 7, 4], [3, 2, 1]]) 
np.mean(F) # Dizideki elemanların aritmetik ortalaması. 

4.5

In [ ]:
np.median(F) # Dizideki elemanların medyanı. 

3.5

In [ ]:
np.max(F) # Dizideki elemanların en büyüğü.

10

In [ ]:
np.min(F) # Dizideki elemanların en küçüğü.

1

In [ ]:
np.var(F)  # Dizideki elemanların varyansı.

9.583333333333334

In [ ]:
np.std(F) # Dizideki elemanların standart sapması.

3.095695936834452

In [ ]:
G = np.arange(4).reshape((2,2))
G

array([[0, 1],
       [2, 3]])

In [ ]:
np.transpose(G) # G matrisinin transpozu

array([[0, 2],
       [1, 3]])

In [ ]:
np.linalg.inv(G) # G matrisinin tersi (inversi)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [ ]:
np.log([1, np.e, np.e**2]) # Verilen dizinin e tabanında logaritması (Neper logaritması - ln fonksiyonu)
# (e sayısı burada da, pi sayısı NumPy kütüphanesinde tanımlıdır.)

array([0., 1., 2.])

In [ ]:
np.log10([1e-15, 1e10]) # Verilen dizinin 10 tabanında logaritması. (1e-15 = 10^-15, 1e10 = 10^10)

array([-15.,  10.])

In [ ]:
np.log2([1, 2, 2**4])  # Verilen dizinin 2 tabanında logaritması.

array([0., 1., 4.])

In [ ]:
np.sin(np.pi/2.)  # Radyan cinsinden verilen açının sinüsü.

1.0

In [ ]:
np.sin(np.array((0., 30., 45., 60., 90.)) * np.pi / 180. ) # Verilen açılar derece cinsinden ise, radyana çevrilmelidir. 

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [ ]:
np.sin(np.array((0., 100., 120.)) * np.pi / 200. ) # Verilen açılar grad cinsinden ise, radyana çevrilmelidir. 

array([0.        , 1.        , 0.95105652])

In [ ]:
np.arcsin(1)     # pi/2'nin arcsinüsü (birim çemberdeki Y koordinatı)

1.5707963267948966

In [ ]:
np.cos(np.array([0, np.pi/2, np.pi])) # Radyan cinsinden verilen açıların kosinüsü.  

array([ 1.000000e+00,  6.123234e-17, -1.000000e+00])

## 3.7 Sayısal Veri Türleri Arasında Dönüşüm
NumPy üzerinde bir dizi atandığında, dizinin içindeki sayısal verilerin türünü de belirleyebiliriz. Bunun için `np.array` fonksiyonu içinde diziyi tanımladıktan sonra, `dtype` argümanını float sayılar için `np.float`, integer sayılar için `np.int`, complex sayılar için `np.complex` şeklinde atamak zorundayız. Örneğin;

In [ ]:
data = np.array([1,2,3], dtype = np.float) # atadığımız dizinin sayısal elemanları float türünde olsun. 
data

array([1., 2., 3.])

`astype()` fonksiyonu ile dizilerin sayısal veri türünü değiştirebilmekteyiz. data dizisi `float` cinsinden sayısal verilere sahipti. Bu dizinin elemanlarını `int` cinsine çevirelim. 

In [ ]:
data.astype(np.int)

array([1, 2, 3])

Float cinsinden bir seri ile complex cinsinden bir seri üzerinde işlem yapıldığında, sonuçlar complex cinsinden olacaktır.

In [ ]:
d1 = np.array([1, 2, 3], dtype = float)
d2 = np.array([1, 2, 3], dtype = complex)
d1 + d2

array([2.+0.j, 4.+0.j, 6.+0.j])

In [ ]:
(d1+d2).dtype # buradan sonucun 128 bit complex sayılardan oluşmuş bir dizi halinde verildiği anlaşılmaktadır.

dtype('complex128')

Dizilere herhangi bir veri türü tayin edilmediğinde, default olarak float türü sayılar atanır. Aşağıdaki dizinin karekökünü almaya çalışalım.

In [ ]:
np.sqrt(np.array([-1, 0 , 1]))

<ipython-input-21-cc10ba3a021e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(np.array([-1, 0 , 1]))


array([nan,  0.,  1.])

Görüleceği üzere dizimizin ilk elemanı -1 float cinsinden atandığı için, karekök fonksiyonu dizide imajiner sayı olmadığı için tanımsızdır ve hata mesajı almaktayız. Aynı diziyi complex sayı olarak yeniden tayin ettiğimizde, dizinin karekökü alınacaktır.

In [ ]:
np.sqrt(np.array([-1, 0 , 1], dtype = complex))

array([0.+1.j, 0.+0.j, 1.+0.j])

## 3.8 Dizileri Yeniden Boyutlandırma

İki listeden oluşan bir NumPy dizisi oluşturalım ve bunu mxn boyutlarında bir matrise dönüştürelim. Bunun için `.reshape(dizi,(m,n))` yöntemi kullanılır. Örneğin; 

In [ ]:
data = np.array([[1, 2], [3, 4]])
np.reshape(data,(1,4))
# data.reshape(1,4)

array([[1, 2, 3, 4]])

In [ ]:
print(data)
print(type(data)) # Görüleceği üzere, orijinal veriyi yaptığımız yeniden boyutlandırma işlemi değiştirmeyecek. data dizisi orijinal haliyle duruyor.

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


In [ ]:
data.reshape(4) # Orijinal diziyi 4 elemanlı bir dizi haline getirelim. 

array([1, 2, 3, 4])

`np.ravel` fonksiyonu, `reshape(n)` fonksiyonunu kullanmadan çok boyutlu bir dizinin tüm satır ve sütunlarını yok ederek, tek boyutlu bir dizi yaratır.

In [ ]:
np.ravel(data)

array([1, 2, 3, 4])

np.flatten fonksiyonu da aynı işlevi görmektedir. Ancak, oluşturulan yeni diziyi kayıt altına almaktadır. 

In [ ]:
data = np.array([[1,2],[3,4]])
data

array([[1, 2],
       [3, 4]])

In [ ]:
data.flatten()

array([1, 2, 3, 4])

In [ ]:
data.flatten().shape

(4,)